#!/snap/platform/current/python/bin/python

from os.path import join
import os, sys
sys.path.append(join(os.environ['SNAP'], 'hooks'))

from hooks.gogs_hooks import install
import logging
from syncloud_app import logger

logger.init(logging.DEBUG, console=True, line_format='%(message)s')

install()