BRAND_NAME = Syncloud
RUN_USER = git
RUN_MODE = prod

[log]
ROOT_PATH = {{.LogPath}}
MODE = console, file
LEVEL = Trace

[log.file]
; Comment out to inherit
; LEVEL =
; Whether to enable automated log rotate (switch of following options).
LOG_ROTATE = true
; Whether to segment log files daily.
DAILY_ROTATE = true
; The maximum size shift of single file, default is 28 means 1 << 28 = 256MB.
MAX_SIZE_SHIFT = 28
; The maximum number of lines of single file.
MAX_LINES = 1000000
; The expired days of log file (delete after max days).
MAX_DAYS = 7

[database]
TYPE = postgres
HOST = {{.DatabaseDir}}:{{.DbPsqlPort}}
NAME = {{.DbName}}
USER = {{.DbUser}}
PASSWORD = {{.DbPassword}}
SSL_MODE = disable

[repository]
ROOT = {{.GogsReposPath}}

[auth]
ENABLE_REGISTRATION_CAPTCHA = false
REQUIRE_SIGNIN_VIEW = true
DISABLE_REGISTRATION = {{.DisableRegistration}}

[server]
DOMAIN = {{.AppDomain}}
EXTERNAL_URL= {{.AppUrl}}
PROTOCOL = unix
HTTP_ADDR = {{.AppDataDir}}/web.socket
UNIX_SOCKET_PERMISSION = 666
APP_DATA_PATH = {{.AppDataDir}}/data

[security]
INSTALL_LOCK = true
SECRET_KEY = {{.WebSecret}}

[picture]
AVATAR_UPLOAD_PATH = {{.DataDir}}/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = {{.DataDir}}/data/repo-avatars
